apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashy
  template:
    metadata:
      labels:
        app: crashy
    spec:
      containers:
      - name: crashy
        image: busybox
        command: ["/bin/sh","-c"]
        args: ["sleep 1; exit 1"]
