apiVersion: descheduler/v1alpha2
kind: DeschedulerPolicy
profiles:
- name: balancing
  pluginConfig:
  - name: LowNodeUtilization
    args:
      thresholds:       {cpu: 20, memory: 20, pods: 20}
      targetThresholds: {cpu: 50, memory: 50, pods: 50}
  - name: RemovePodsViolatingTopologySpreadConstraint
  - name: RemovePodsViolatingInterPodAntiAffinity
  - name: RemoveDuplicates
  plugins:
    balance:
      enabled:
      - LowNodeUtilization
    deschedule:
      enabled:
      - RemovePodsViolatingTopologySpreadConstraint
      - RemovePodsViolatingInterPodAntiAffinity
      - RemoveDuplicates
