grafana:
  enabled: true

alertmanager:
  alertmanagerSpec:
    # Mount the secret as files under /etc/alertmanager/secrets/<secret-name>/*
    secrets:
      - am-slack-webhook
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: slack-default
      group_by: [alertname, namespace]
      group_wait: 10s
      group_interval: 2m
      repeat_interval: 3h
      routes:
        - matchers: [ severity="critical" ]
          receiver: slack-critical
        - matchers: [ severity="warning" ]
          receiver: slack-warning
        - matchers: [ severity="info" ]
          receiver: slack-info
    inhibit_rules:
      - source_matchers: [ severity="critical" ]
        target_matchers: [ severity="warning" ]
        equal: [ alertname, namespace ]
    receivers:
      - name: slack-default
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/am-slack-webhook/slack_api_url
            send_resolved: true
            title: |-
              [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity | default "info" }})
            text: |-
              Namespace: {{ .CommonLabels.namespace | default "cluster-wide" }}
              Summary: {{ .CommonAnnotations.summary | default "n/a" }}
              Description: {{ .CommonAnnotations.description | default "n/a" }}
      - name: slack-critical
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/am-slack-webhook/slack_api_url
            channel: "#k8s-critical"
            send_resolved: true
            title: |-
              :rotating_light: [CRITICAL] {{ .CommonLabels.alertname }}
            text: |-
              Namespace: {{ .CommonLabels.namespace | default "cluster-wide" }}
              Summary: {{ .CommonAnnotations.summary | default "n/a" }}
              Description: {{ .CommonAnnotations.description | default "n/a" }}
      - name: slack-warning
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/am-slack-webhook/slack_api_url
            channel: "#k8s-alerts"
            send_resolved: true
            title: |-
              [WARNING] {{ .CommonLabels.alertname }}
            text: |-
              Namespace: {{ .CommonLabels.namespace | default "cluster-wide" }}
              Summary: {{ .CommonAnnotations.summary | default "n/a" }}
      - name: slack-info
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/am-slack-webhook/slack_api_url
            channel: "#k8s-info"
            send_resolved: false
