apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-health-basic-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: kube-health.rules
    rules:
    - alert: NodeNotReady
      expr: min(kube_node_status_condition{condition="Ready",status="true"}) by (node) < 1
      for: 2m
      labels: { severity: critical }
      annotations:
        summary: "Node not Ready"
        description: "Node {{ .node }} has not been Ready for 2m."

    - alert: PodNotReady
      expr: min(kube_pod_status_ready{condition="true"}) by (namespace,pod) < 1
      for: 5m
      labels: { severity: warning }
      annotations:
        summary: "Pod not Ready"
        description: "Pod {{ .namespace }}/{{ .pod }} not Ready for 5m."

    - alert: HighPodRestarts
      expr: increase(kube_pod_container_status_restarts_total[10m]) > 5
      for: 0m
      labels: { severity: warning }
      annotations:
        summary: "High container restarts"
        description: "{{ .namespace }}/{{ .pod }} restarts spiking over last 10m."
